export const vibePrompts: Record<string, string> = {
  coquette:
    "Create an unbelievably beautiful romantic fantasy world around the original subject, like an enchanted rose palace garden during the last moments of golden sunset. Surround the scene with enormous blooming blush roses, delicate pale pink peonies, cascading flower arches and soft ivory blossoms, with elegant flowing ribbons drifting gently through the air. Build a luxurious layered environment with dreamy flowers softly blurred in the foreground, a luminous garden surrounding the subject in the midground, and an elegant glowing palace garden fading into the background. Warm champagne sunlight streams through the flowers in delicate rays, creating luminous highlights, creamy bokeh and tiny sparkling particles floating through the air. Add subtle satin textures, pearlescent reflections and tiny crystal-like highlights throughout the environment. Use an exquisite palette of blush pink, rose, ivory, champagne and soft peach. The final scene should feel romantic, feminine, magical, luxurious and impossibly beautiful, like a breathtaking beauty campaign photographed inside a fairytale. Photorealistic, cinematic depth, soft dreamy atmosphere, exquisite lighting and premium editorial photography. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",

  "dark-luxury":
    "Create an extraordinarily luxurious midnight fantasy world around the original subject, inside an enormous elegant palace illuminated by moonlight and warm golden candlelight. Surround the environment with deep burgundy roses, black velvet curtains, glossy obsidian marble, delicate antique gold details and hundreds of tiny warm lights disappearing into the distance. Create dramatic cinematic layers with dark blurred flowers in the foreground, the luxurious subject environment in the center, and a grand shadowy palace fading into the background. Add subtle golden reflections across the polished surfaces, delicate floating dust particles illuminated by narrow beams of light, soft atmospheric haze and deep luminous shadows. Introduce rich burgundy, black, espresso, antique gold and deep plum tones with controlled highlights. The scene should feel mysterious, sensual, sophisticated and extraordinarily expensive, like an exclusive luxury campaign photographed inside a midnight palace. Photorealistic, cinematic, dramatic depth, luxurious lighting, polished reflections and breathtaking editorial composition. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",

  botanical:
    "Create an extraordinarily beautiful hidden botanical paradise surrounding the original subject, like a secret glass greenhouse discovered inside an enchanted garden at sunrise. Surround the scene with enormous tropical leaves, delicate white orchids, tiny wildflowers, climbing vines, soft moss, translucent leaves covered with morning dew and elegant botanical arches. Build multiple layers of depth with softly blurred leaves and flowers in the foreground, lush vegetation surrounding the subject in the midground, and a glowing glass greenhouse disappearing into a misty garden in the distance. Golden morning sunlight passes through the glass ceiling and leaves, creating magical volumetric rays, glowing dew drops, luminous green highlights and soft circular bokeh. Add tiny floating pollen particles and subtle morning mist catching the sunlight. Use an exquisite palette of emerald, sage, fresh green, ivory and warm champagne. The environment should feel alive, peaceful, luxurious and almost impossibly beautiful, like a dreamlike botanical editorial photographed in a secret paradise. Photorealistic, cinematic depth, natural luxury, ethereal lighting and breathtaking composition. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",

  dreamy:
    "Create an unbelievably beautiful ethereal fantasy world around the original subject, like a magical lavender garden beside a perfectly calm glowing lake under a luminous twilight sky. Surround the scene with thousands of delicate lavender and lilac flowers, soft purple blossoms, floating translucent petals and tiny luminous particles drifting through the air. Create extraordinary cinematic depth with dreamy flowers softly blurred in the foreground, the original subject surrounded by glowing petals in the center, and a vast magical lavender garden fading toward the horizon in the background. A perfectly still reflective water surface catches the soft lavender and pearlescent light, creating shimmering reflections beneath the scene. Add gentle floating mist, tiny sparkling particles, soft glowing orbs and subtle moonlit haze throughout the environment. Use an exquisite palette of lavender, lilac, pearl white, blush pink and soft violet with luminous highlights and delicate shadows. The lighting should feel magical and dimensional, with soft volumetric moonlight filtering through the atmosphere and glowing reflections surrounding the subject. The final image should look like an impossible fairytale captured as a luxury fragrance campaign, breathtakingly beautiful, dreamy, elegant, magical and surreal while remaining photorealistic. Cinematic photography, extraordinary depth, ethereal atmosphere, luminous bokeh, exquisite composition and premium editorial finish. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",

  y2k:
    "Create an extraordinarily beautiful futuristic Y2K fantasy world around the original subject, like an iridescent dream palace floating inside a soft luminous universe. Surround the environment with curved chrome architecture, translucent glass, liquid-metal surfaces, pearlescent reflections, holographic textures and delicate floating crystal spheres. Build cinematic layers with soft reflective shapes in the foreground, the subject surrounded by glowing iridescent surfaces in the center, and a vast futuristic dreamscape fading into the background. Use subtle pastel neon illumination in icy blue, lavender, baby pink, silver and pearl, creating beautiful reflections across every surface. Add floating translucent bubbles, tiny holographic particles, soft lens flares and glowing atmospheric haze. The lighting should feel like a combination of dreamy studio flash and luminous futuristic ambient light, creating soft highlights without becoming harsh. The environment should feel glamorous, nostalgic, futuristic and unbelievably beautiful, like a luxury Y2K fragrance campaign from an alternate dream universe. Photorealistic, cinematic depth, pearlescent lighting, sophisticated futuristic design and breathtaking editorial composition. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",

  minimal:
    "Create an impossibly beautiful serene luxury world around the original subject, like an elegant sculptural palace floating above soft clouds at sunrise. Surround the scene with flowing ivory architectural forms, smooth cream stone, delicate translucent curtains, subtle pearlescent surfaces and extremely refined sculptural details. Create extraordinary depth with soft architectural shapes in the foreground, the original subject beautifully illuminated in the center, and an expansive luminous cloudscape fading into the distance. Warm sunrise light flows through the environment in soft volumetric beams, creating delicate champagne highlights, creamy shadows and subtle glowing reflections. Add a few extremely delicate floating petals and tiny luminous particles while preserving the clean sophisticated composition. Use a refined palette of ivory, cream, pearl, champagne and the faintest blush pink. The final scene should feel serene, heavenly, expensive and almost unreal, like a luxury beauty campaign photographed inside a floating cloud palace. Photorealistic, cinematic depth, soft volumetric lighting, exquisite negative space and breathtaking minimalist editorial composition. Keep the original subject completely unchanged in shape, identity, colors, position and important details.",
};